### ISSUE TITLE
Script stops on "unable to find chilli interface tun0".

### ISSUE THREAD

**Issue by scottie** [pihomeserver/Pi-Hotspot-Script#14]
Ran script from _FRESH Raspian install_.
Everything works well till i run into this error near end of script:

Stops on "**unable to find chilli interface tun0**".

ifconfig shows no tun0.

**pastebin.com/PscgBhiV**

A fresh install of latest RASBIAN shows no module TUN if one types "lsmod".
"sudo modprobe tun" gives error

**Comment by scottie** [comment]
A fresh install of latest RASBIAN shows no module TUN if one types "lsmod".

**Comment by scottie** [comment]
"sudo modprobe tun" gives error

**Comment by scottie** [comment]
**_FIXED instructions here:_**
http://superuser.com/questions/497245/how-to-load-tun-module-in-linux

**Comment by pihomeserver** [comment]
I guess that's an issue with the full Raspbian as i never got it with the net install version
