### ISSUE TITLE
What to do after install in README

### ISSUE THREAD

**Issue by scottie** [pihomeserver/Pi-Hotspot-Script#16]
What does one do after a install?
Does one need to configure in the radius GUI ?

**Add Hotspot**
Go to Management Tab > Hotspots > Click New Hotspot
Enter Hotspot Name and MAC Address of interface connected to clients, Click Apply

**Add NAS**
Go to Management > Nas > Click New NAS
Enter NAS Info, IP, NAS secret (e.g. testing123), NAS type, Other and NAS shortname. Set NAS Ports to 3997, Click Apply

Or it should all just work out of the box after script is ran ?

**Comment by pihomeserver** [comment]
Hello

I never had to create Hotspot or NAS to get it work. Did you tested without any ?
