### ISSUE TITLE
prepaid user setup

### ISSUE THREAD

**Issue by reigelgallarde** [pihomeserver/Pi-Hotspot-Script#19]
hello, thank you for the script, it's working.

I have a question though, how to setup/create a user with 1 hour limit?

**Comment by pihomeserver** [comment]
Hello

Please look at Daloradius functions. An exemple of configuration that seems to work : https://ubuntuforums.org/showthread.php?t=2070298&highlight=daloradius

You have to create counters that will consolidate the time and volume of a connected user (section FreeRadius SQL counter.conf settings needed)

Then you create profiles linked to the counters and apply to the user (section daloRADIUS 0.9-9 – QUCIK START)

Hope it helps

**Comment by reigelgallarde** [comment]
ok, thanks... I will try this...

I hope you can add this also on the script... would be very useful for everyone...

**Comment by pihomeserver** [comment]
Yes that's a good idea. At least I can add the counters creation.

**Comment by reigelgallarde** [comment]
I was not able to make it work on my first try. Haha. Just not my thing.
I hope you can update the script and add this kind of functionality.

I will however try again until it works. 😄

**Comment by pihomeserver** [comment]
Yesterday I updated configuration files. Hope that today I will be able to create attributes in daloradius and test them

**Comment by reigelgallarde** [comment]
great! wish you good luck!

**Comment by reigelgallarde** [comment]
hello, have you got any luck on this one?

anyway, I have tested your new script on a fresh install of minibian, and I think it got some error...
freeradius is not running...
I tried calling `service freeradius start` and it won't start... 
searching at Google I found and tried to call `freeraduis -X`
freeradius will still not run... something with ports being used chilli. 

I then remove coa like `rm /etc/freeradius/sites-enabled/coa`
do a reboot, then all starts working... not sure what's wrong.

**Comment by pihomeserver** [comment]
Updated. The Coova CoA port was in conflict with the freeradius support that is not required.

The new script activates defaults SQL counters. Look here for implementation : https://wiki.freeradius.org/modules/Rlm_sqlcounter

Please tell me if it works

**Comment by reigelgallarde** [comment]
yes, this one works... I tried it earlier... using mysql commands....

what's not working is daloradius... it seems daloradius does not have the correct sql command... I'm not sure...

**Comment by pihomeserver** [comment]
Ok if both of us can investiguate we should be able to find a way.
I will put on side the Squid integration for now to come back on this point

**Comment by pihomeserver** [comment]
Checked daloradius and the radcheck table content and the attribute is well created but not taken into account to disconnect the user
<img width="468" alt="capture d ecran 2017-03-09 a 19 12 39" src="https://cloud.githubusercontent.com/assets/3817578/23764064/7194b58c-04fc-11e7-99c9-038bbaa3b170.png">

**Comment by pihomeserver** [comment]
In progress :
1) Edit /etc/freeradius/sites-enabled/default and uncomment line 192 to authorize daily counter
2) Restart freeradius
3) In daloradius add one attribute using the daloradius dictionary

<img width="590" alt="capture d ecran 2017-03-10 a 22 07 15" src="https://cloud.githubusercontent.com/assets/3817578/23813190/fccfc542-05dd-11e7-95ca-fadad6aa1968.png">

For now i got disconnected after 30 seconds but able to reconnect ...
