### ISSUE TITLE
Unable to find chilli interface tun0

### ISSUE THREAD

**Issue by NiranjanKumarJakka** [pihomeserver/Pi-Hotspot-Script#33]
I have tried in Pi-Hotspot-Script in raspbian jessie lite, i got this error can any one please help me

error: Unable to find chilli interface tun0

**Comment by pihomeserver** [comment]
Please look at issue #14

**Comment by pihomeserver** [comment]
After a dist upgrade and reboot i do not have the issue. It's integrated in the next release of the script

**Comment by reigelgallarde** [comment]
I have this issue before. And found out that if you enable the wifi first before running the script, you will not face this problem.
