### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Saulgodman** [pihomeserver/Pi-Hotspot-Script#6]
i have an error

`./pihotspot.sh: line 265: syntax error near unexpected token `('
./pihotspot.sh: line 265: `display_message " (login : administrator / password : radius)"'
`

or

`./pihotspot.sh: line 265: unexpected EOF while looking for matching `"'
./pihotspot.sh: line 266: syntax error: unexpected end of file
`

**Comment by pihomeserver** [comment]
Hello
Not sure what script you are using at line 265 is not this command. Take the latest version and try again.

**Comment by Saulgodman** [comment]
Hello,

Strange I use the latest version on Minibian.

:(

**Comment by pihomeserver** [comment]
Look at the source on GitHub and you will see that the line number does not get the instruction with the error
By the way if you reach this display line, it means that the hotspot is up and fully configured

**Comment by Saulgodman** [comment]
Mh. Here is a picture of a clean installation.

[https://owncloud.blungogo.de/index.php/s/a8xchAOXo4hTC4y](url)

**Comment by pihomeserver** [comment]
Ok one " is missing in the new instruction for Pi 2
Can you please give a new try ?

**Comment by Saulgodman** [comment]
Yes now it runs! :)

Thank you very much
